### ISSUE TITLE
SDL Mixer breaks on compilation

### ISSUE THREAD

**Issue by eriktate** [nim-lang/sdl2#107]
When trying to build a project using SDL mixer the build fails because of a `when 0:` at line 451 of `sdl2/mixer.nim`

Error message below:
`../../../.nimble/pkgs/sdl2-1.2/sdl2/mixer.nim(451, 6) Error: type mismatch: got <int literal(0)> but expected 'bool'`

**Comment by krux02** [comment]
you can create a PR to fix it.

Alternatively there is also another SDL2 wrapper here: https://github.com/Vladar4/sdl2_nim
From my personal experience it a better wrapper than this "official" one.

**Comment by eriktate** [comment]
Already done! And I see you've already approved it :smile: Thanks for the quick turn around! Closing this now
