### ISSUE TITLE
add CI testing (eg via travis)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/sdl2#111]
/cc @krux02 
this would've caught the regression I'm fixing https://github.com/nim-lang/sdl2/pull/110

**Comment by krux02** [comment]
I am not adding travis integration here, sorry. Graphical applications can't automatically be tested.

**Comment by krux02** [comment]
I like automated testing, but here I really disagree. It is too much bureaucracy with too little gain. If an issue like the last one happens again, then I will change my mind, but until then, no unit testing. I don't plan to add any features to this wrapper.

**Comment by yglukhov** [comment]
Yeah, no hard feelings.

**Comment by timotheecour** [comment]
all right, a tool implementing https://github.com/nim-lang/Nim/issues/8638 would be a better fix, requiring 0 work for existing repos
* it would run `nimble test` for whiltelisted repos that have a `nimble test` section
* it would run `nim check <mainfile.nim>` for whiltelisted repos that don't have a `nimble test` section
