### ISSUE TITLE
use versioning scheme a.b.c.d: a.b.c - underlying library version;  d: wrapper revision

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/sdl2#113]
this is in response to https://github.com/nim-lang/sdl2/pull/112#issuecomment-436763534

@yglukhov 
> I have just re-released the v2.0 version. It was not usable anyway, so there's nothing to lose.
```
git fetch
git checkout v2.0
git rev-parse HEAD
```
still points to the old ad9a91ed2d92a2c018dc90c0b0d434af4688e174 before the fix

/cc @krux02 
> sorry I won't update the version over the version of the original sdl2 library. I see the last release as a failed release

how will that work with nimble users ? /cc @dom96 

if a user already has `~/.nimble/pkgs/sdl2-2.0/`  (perhaps after running `nimble install foo` for a package `foo` that had `requires "sdl2 >= 2.0"` as a dependency), then any subsequent change in nim-lang/sdl2 repo won't be taken into account UNLESS `foo` specifies a HEAD version of sdl2, eg `requires "sdl2#head"` which as you know has other issues (not reproducible builds, instability etc)

Instead, a better scheme is the versioning scheme done here https://github.com/Vladar4/sdl2_nim#versioning-scheme

a.b.c.d

a.b.c - underlying SDL2 version
d     - sdl2_nim revision

**Comment by yglukhov** [comment]
This should work:
```
git fetch --tags --prune-tags upstream
```
Note that the vast majority of users should not be affected by this

**Comment by timotheecour** [comment]
> This should work:

ok thx (so does a fresh clone)

> Note that the vast majority of users should not be affected by this

I'm not worried about users affected by the particular bug fixed by https://github.com/nim-lang/sdl2/pull/110  ; I'm talking about all future bugfixes and having a versioning scheme that would allow patching a versioned nim wrapper. The `a.b.c.d` versioning scheme covers all the of these future cases. 

That's a lot more users

**Comment by krux02** [comment]
@timotheecour if you want that version scheme just use https://github.com/Vladar4/sdl2_nim

**Comment by timotheecour** [comment]
that's not viable solution for packages that rely on `sdl2` instead of `sdl2_nim` (there are differences between these)
I've explained the arguments in favor of `a.b.c.d`  for any wrapper lib (including sdl2 nimble package) that tracks a library version `a.b.c` ; and I explained why simply using upstream's versioning (`a.b.c`) is inadequate. 

please explain what would be drawbacks of that versioning scheme

**Comment by Araq** [comment]
The ``.d`` part doesn't capture semantic versioning at all, wrappers can grow features too... Btw SDL2 itself doesn't use semantic versioning, 2.0.3 added important features.

**Comment by timotheecour** [comment]
you're missing my main point:
if a nim wrapper tracks a library at version x.y.z (eg 2.0.3) is itself versioned as x.y.z, then changes to the nim wrapper (eg bugfixes) (tracking same library version 2.0.3) can't be tagged with a new version, so tools like nimble won't be able to pickup the corresponding release with bugfixes in the wrapper.
Whereas with a.b.c.d scheme, you can now target `"requires foo >= 2.0.3.1"`)

**Comment by Araq** [comment]
The Nimble version shouldn't be based on the version of the originally wrapped library, that ignores how the Nim wrapping mechanism works. Only accessed symbols are ``dlsym``'ed so wrapping SDL 2.0.10 and accessing a SDL_2.0.1.dll works as long as you don't use a feature that 2.0.1 lacks.

**Comment by timotheecour** [comment]
so we're running in circles ; my previous PR to bump the version hit a wall: https://github.com/nim-lang/sdl2/pull/112#issuecomment-436763534 
> sorry I won't update the version over the version of the original sdl2 library. I see the last release as a failed release

I'm fine with either a.b.c.d OR independent version x.y.z for wrapping a library a.b.c ;  but I'm not fine with current version scheme used in https://github.com/nim-lang/sdl2 , where the current policy by @krux02 was:
> sorry I won't update the version over the version of the original sdl2 library
