### ISSUE TITLE
Emscripten support?

### ISSUE THREAD

**Issue by JaviCervera** [nim-lang/sdl2#134]
I'd like to use Nim and this bindings to make a web game build with Emscripten, but it does not seem to work. I got the Nim program to build correctly, but when launching the generated program in the browser, I get the error:

```
To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking
```

I suspect this is due to the bindings trying to open libSDL2.so, which should not be done in Emscripten. In the linker flags, I already specify linking with SDL2 the way it should be done in Emscripten, with `-s USE_SDL=2`. Is there a way to force the bindings in Linux to assume SDL2 is statically linked and not try to open libSDL2.so? Or, is there another official approach for Emscripten?

**Comment by dom96** [comment]
Here is how I built my game for emscripten.

In nim.cfg:

```
@if emscripten:
          --nimcache:"./emscripten"
          --dynlibOverride:SDL2
          --dynlibOverride:SDL2_image
          --passC:"-O3 -Lemscripten -s USE_SDL=2"
          --passL:"-s USE_SDL=2 -s USE_SDL_IMAGE=2 -s TOTAL_MEMORY=536870912 -s SAFE_HEAP=1 -s WARN_UNALIGNED=1 --use-preload-plugins --preload-file out --preload-file fonts"
          --genScript
          --os:linux
          --cpu:i386
          --cc:clang
          --clang.exe:emcc
        @end
````

Then `nim c -d:emscripten -d:noSignalHandlers client.nim`

You can also have a look at https://github.com/def-/nimes

**Comment by JaviCervera** [comment]
Great! Adding --dynlibOverride:SDL2 to my config worked, since I already had the rest. Thank you very much!
