### ISSUE TITLE
I don't see syntax highlighting on sdl2.nim file on github

### ISSUE THREAD

**Issue by james-guevara** [nim-lang/sdl2#135]
Just letting you know I don't see syntax highlighted here for some reason:

https://github.com/nim-lang/sdl2/blob/master/src/sdl2.nim

**Comment by Araq** [comment]
Yeah, it happens occasionally, probably because github uses heuristics for language detection rather than using the file extension. But we cannot fix github bugs.

**Comment by dom96** [comment]
Probably best to report it here: https://github.com/github/linguist/
