### ISSUE TITLE
Create tag for v2.0.4

### ISSUE THREAD

**Issue by metagn** [nim-lang/sdl2#143]
[The version was bumped to 2.0.4](https://github.com/nim-lang/sdl2/commit/9f41e6232cbe9ad9ee4ba8dcc49e93edcc84b889), however [there is no v2.0.4 tag](https://github.com/nim-lang/sdl2/tree/v2.0.4), instead the latest tag is [v2.0.3](https://github.com/nim-lang/sdl2/tree/v2.0.3).

**Comment by ringabout** [comment]
Done, is bumping the version not sufficent?

**Comment by metagn** [comment]
Nimble doesn't consider it a new release without a tag, seems to now though. Thanks

**Comment by ringabout** [comment]
@metagn Hi, sdl2.0.4 seems to break something

**Comment by ringabout** [comment]
.................................................................................................................
  /Users/runner/.nimble/pkgs/sdl2-2.0.4/sdl2/joystick.nim(200, 35) Error: invalid token: trailing underscore

**Comment by ringabout** [comment]
find the culprit => https://github.com/nim-lang/sdl2/pull/140#issuecomment-1211636711

**Comment by ringabout** [comment]
I removed tag and made a fix => https://github.com/nim-lang/sdl2/pull/144

**Comment by metagn** [comment]
Tag again?

**Comment by metagn** [comment]
Again, can the tag be created now?

**Comment by ringabout** [comment]
done https://github.com/nim-lang/sdl2/releases/tag/v2.0.4
