### ISSUE TITLE
sdl_audio_callback.nim specifies too large buffer

### ISSUE THREAD

**Issue by triplefox** [nim-lang/sdl2#15]
Line 59: audioSpec.samples = BufferSizeInBytes
changed to
audioSpec.samples = BufferSizeInSamples

Fixes a local issue where the test tone cuts out.

**Comment by trustable-code** [comment]
When I try to compile your gist with Nim 0.10.2, I get:
Line 71: Error: undeclared identifier: 'BufferSizeInSamples'

Back to the basic problem:
For me only this works: audioSpec.samples = BufferSizeInBytes
For you only that works: audioSpec.samples = BufferSizeInSamples
How can we solve this?

**Comment by triplefox** [comment]
My apologies for posting broken code. Please try this one, it follows the original example as closely as I could get it.
https://gist.github.com/triplefox/45c8ffebc0d6301d525d

**Comment by trustable-code** [comment]
Good. This one works for me too.
Solution: Store obtained buffer size and use this instead of specified buffer size.
Can you please make a pull request?

**Comment by trustable-code** [comment]
Solved by https://github.com/nim-lang/sdl2/pull/18
