### ISSUE TITLE
Adding a wrapper for WINDOWPOS_UNDEFINED

### ISSUE THREAD

**Issue by yumaikas** [nim-lang/sdl2#16]
I've started going though this [tutorial](http://lazyfoo.net/SDL_tutorials/lesson01/index2.php) and found that there was no wrapper for  passing `WINDOWPOS_UNDEFINED` to [`SDL_CreateWindow`](http://wiki.libsdl.org/SDL_CreateWindow). When I find the time to figure it out (new to both Nim and SDL), I'll send a pull request.

**Comment by Varriount** [comment]
If you need help, don't be afraid to ask, here or on IRC

**Comment by fowlmouth** [comment]
fixed in 1982d24
