### ISSUE TITLE
No SDL_PIXELFORMAT_* enum?

### ISSUE THREAD

**Issue by jyapayne** [nim-lang/sdl2#21]
Hey!

Great work with the SDL 2.0 bindings :) 

I was wondering why there was no SDL_PIXELFORMAT_ARGB8888 specifically, but it seems that whole enum is missing. Is there a design decision here that I'm missing?

Cheers,
Joey

**Comment by fowlmouth** [comment]
they were probably overlooked. there are other enums, macros related to the pixel format, if any of these values are platform-dependent that would have to be represented in the wrapper too.
https://wiki.libsdl.org/SDL_PixelFormatEnum

if you like, you can send a PR. please add them as `const`s to avoid having to change it in the future like issue #9
