### ISSUE TITLE
Warning: undeclared conditional's

### ISSUE THREAD

**Issue by G4MR** [nim-lang/sdl2#25]
c:\users\....\.nimble\pkgs\sdl2-1.0\sdl2.nim(501, 12) Warning: undeclared conditional symbol; use --symbol to declare it: SDL_Static [User]
    c:\users\....\.nimble\pkgs\sdl2-1.0\sdl2.nim(1393, 12) Warning: undeclared conditional symbol; use --symbol to declare it: iPhone [User]
    c:\users\....\.nimble\pkgs\sdl2-1.0\sdl2.nim(1419, 12) Warning: undeclared conditional symbol; use --symbol to declare it: android [User]

Seems like this could be a workaround for that warning https://github.com/Araq/Nim/issues/1704

**Comment by def-** [comment]
This warning was added for the split betwenn `defined` and `declared`. It will be removed at some point, so I don't think it's worth worrying about.

**Comment by yglukhov** [comment]
These warnings have been fixed in nim compiler, haven't they?

**Comment by yglukhov** [comment]
Afaik its fixed. Please reopen otherwise.
