### ISSUE TITLE
Byte order issue for colors on SDL2/gfx

### ISSUE THREAD

**Issue by qrpc** [nim-lang/sdl2#32]
source says:
 # Note: all ___Color routines expect the color to be in format 0xRRGGBBAA
Tested on a pair of intel Macs and it expects 0xAABBGGRR

**Comment by fowlmouth** [comment]
@qrpc are all the colors in SDL2 like that? (I mean not just the ones used from gfx module)
If so, we need a version of `SDL_FOURCC` for mac

**Comment by qrpc** [comment]
I see the non-gfx SDL2 colors given separately as r, g, b, a, not a single unit32 how should I test that?
(SDL colors work normally)

**Comment by fowlmouth** [comment]
use SDL_FOURCC to make a blue or green color, try it with something from the gfx addon. This is really a sdl2_gfx problem though

**Comment by qrpc** [comment]
These produce the same color: 
 render.rectangleColor(25,25,100,100, 0xFFFF0000) 
 render.rectangleColor(35,35,130,130, SDL_FOURCC(0,0,255,255))

**Comment by fowlmouth** [comment]
When I try that it is blue, what color is it for you?

**Comment by qrpc** [comment]
Both are blue. The comment says "Color routines expect the color to be in format 0xRRGGBBAA" it this case its  endianness is flipped to "0xAABBGGRR".

**Comment by fowlmouth** [comment]
Ah ok so that comment was from one of the sdl2_gfx headers, if you want to change it you can do a pull request.
