### ISSUE TITLE
Calling the 'close' closure member of RWopsPtr throws an illegal storage access error

### ISSUE THREAD

**Issue by G4MR** [nim-lang/sdl2#37]
Error:

    example.nim(33)          :anonymous
    image.nim(90)            close
    image.nim(93)            close
    SIGSEGV: Illegal storage access. (Attempt to read from nil?)
    Error: execution of an external program failed

Source:

    import sdl2, sdl2.image as img
    import helpers

    import typetraits

    type Image* = ref object
        rw*: RWopsPtr
        format: string
        loaded: bool
        surface: SurfacePtr
        texture: TexturePtr
        src_rect: Rect
        dst_rect: Rect

    method getFormat*(self: Image): string =
        if isNil(self.format):
            "none"
        else:
            self.format

    method isLoaded*(self: Image): bool = 
        self.loaded

    method setDimensions*(self: Image; src, dst: Rect) =
        self.src_rect = src
        self.dst_rect = dst

    method setDimensions*(self: Image; src, dst: tuple[x, y: int; w, h: int]) =
        self.setDimensions(toRect(src), toRect(dst))

    method setSrc*(self: Image, src: Rect) =
        self.src_rect = src

    method setSrc*(self: Image, src: tuple[x, y: int; w, h: int]) =
        self.setSrc(toRect(src))

    method setDst*(self: Image, dst: Rect) =
        self.dst_rect = dst

    method setDst*(self: Image, dst: tuple[x, y: int; w, h: int]) =
        self.setDst(toRect(dst))

    method load*(self: Image, file: cstring, render: RendererPtr) =

        self.loaded = false
        self.rw = sdl2.rwFromFile(file, "rb")

        if not isNIl(self.rw):
            if img.isGIF(self.rw) == 1:
                self.format = "gif"
            elif img.isPNG(self.rw) == 1:
                self.format = "png"
            elif img.isJPG(self.rw) == 1:
                self.format = "jpg"
            elif img.isBMP(self.rw) == 1:
                self.format = "bmp"
            elif img.isWEBP(self.rw) == 1:
                self.format = "webp"
            else:
                self.format = nil

        if isNil(self.rw):
            echo "yes..."

        if not isNil(self.format):

            # try loading surface
            self.surface = img.load_RW(self.rw, 1)
            if isNil(self.surface):
                #throw exception
                return

            #try loading texture
            self.texture = sdl2.createTextureFromSurface(render, self.surface)
            if isNil(self.texture):
                #throw exception
                return

            self.loaded = true

    method draw*(self: Image, render: RendererPtr) =
        
        if isNil(self.texture):
            return

        # draw font to screen
        sdl2.copy(render, self.texture, addr(self.src_rect), addr(self.dst_rect))

    # Release any resources used by the stream and free RWopsPtr memory
    method close*(self: Image) =

        if not isNil(self.rw):
            let close_rw = self.rw.close(self.rw)
            #echo "closed successfully"

        if not isNil(self.surface):
            destroy self.surface

        if not isNil(self.texture):
            destroy self.texture

Usage:

    var img = Image()
    img.load("example.jpg", sdl_renderer)

    .. loop ..

    img.close()

**Comment by yglukhov** [comment]
@G4MR, have you tried with the latest master? It should have been fixed with 1fc0a6ca0013dc5fd4bf464c116fd69acd80d4a3.

**Comment by G4MR** [comment]
Yeah I've downloaded latest @#head through nimble and updated nim to the latest devel.  It executes fine, but once the window closes it throws that Traceback, only on the line where `close` is being called.

Maybe you can add [`SDL_FreeRW`](https://wiki.libsdl.org/SDL_FreeRW) as `freeRW` and I'll just manually do it?

**Comment by fowlmouth** [comment]
The error is because the close field is somehow empty, I'm not sure why this would be. Luckily, you can load an image without RWops and you dont need to store RWops (or the surface) in an Image here at all
```nim
import sdl2/img
let surf = img.load("file.bmp")
if surf.isNil: 
  # handle it
let tex = createTextureFromSurface(surf)
destroy surf
```

**Comment by G4MR** [comment]
Yeah I know I don't need RWops, but that's not really the point of what I'm trying to do.  Rwops gives you a few more features than just loading a texture or what not.  If I can't figure out how to fix the error then I'll just do it the normal way.

**Comment by yglukhov** [comment]
Ah, OK, img.load_RW closes your RWOps =))).

**Comment by G4MR** [comment]
oh my god, I'm retarded.  Thanks.

**Comment by fowlmouth** [comment]
@yglukhov does it need to be free'd after that? (Do we need the allocRW/freeRW functions available?)

**Comment by G4MR** [comment]
@fowlmouth load_RW free's it if the 2nd parameter is set to anything greater than 0 iirc.  So no you don't need to free it after that, but freeRW should still be available.  The binding should be as complete as possible imho.
