### ISSUE TITLE
Convenience template for per-frame key handling

### ISSUE THREAD

**Issue by transfuturist** [nim-lang/sdl2#39]
```
template down(keys: ptr array[0 .. SDL_NUM_SCANCODES.int, uint8], key: cint): expr =
  keys[uint8(getScancodeFromKey(key))] != 0
```

Please add to the library to make per-frame key handling more concise. From [LazyFoo.](http://lazyfoo.net/tutorials/SDL/18_key_states/index.php)

**Comment by fowlmouth** [comment]
sdl2 already has this
```nim
sdl2.getKeyboardState()[int(getScancodeFromKey(key))]
```

**Comment by transfuturist** [comment]
That should work.

**Comment by krux02** [comment]
this is just a wrapper. I won't try to fix anything from the original API. If you want that template you can define it locally, but there is no need for it in this wrapper.
