### ISSUE TITLE
SDL2 quit and init / cimport naming convention

### ISSUE THREAD

**Issue by victor-rene** [nim-lang/sdl2#49]
I just installed nim today. Problem is I can compile:

```
import sdl2, sdl2/image as sdl2_image
...
discard sdl2_image.quit
```

But I can not compile:

```
discard sdl2.quit
```

This results in: "Error: internal error: expr(nkClosedSymChoice); unknown node kind".
I guess there is a conflict between:
https://github.com/nim-lang/sdl2/blob/master/src/sdl2.nim#L620
and
https://github.com/nim-lang/sdl2/blob/master/src/sdl2.nim#L823

I am not sure I like to have C names changed (prefiix removed), because with names like init quit load, etc... I need to type the module name anyways to resolve ambiguity, which is kind of pointless. And I don't think SDL names can conflict with any name in nim. Also #23 . My 2 cents

**Comment by victor-rene** [comment]
Confirmed. Changing imported name from

    proc quit* {.
      importc: "SDL_Quit".}

to

    proc sdl_quit* {.
      importc: "SDL_Quit".}

compiles.

**Comment by dom96** [comment]
I'd say this is a Nim compiler bug. Can you report it on nim-lang/Nim?

**Comment by victor-rene** [comment]
Your example https://github.com/nim-lang/sdl2/blob/master/examples/sdl_skeleton.nim uses "window" identifier. But then you also use the "window" identifier for WindowEventPtr at https://github.com/nim-lang/sdl2/blob/master/src/sdl2.nim#L596

This is two cases of using common names for events causing conflicts. It has nothing to do with nim compiler, I am almost certain.

**Comment by dom96** [comment]
An internal error is always a compiler bug.

**Comment by victor-rene** [comment]
Whatever you think. I won't try to convince you. I'm modifying those templates to use evquit instead of quit and evwindow instead of window. There is no reason why you might think it's normal to cause conflicts by choosing names who are obviously going to clash when the compiler applies the template. Can't you understand there is already a proc named quit and then you add a template who is creating another quit proc ??? You can close issue if you like. I know what's going on.

**Comment by dom96** [comment]
I do understand that. I'm not going to close this, it's a bug in sdl2 as well. But the error you got is also a compiler bug.

**Comment by krux02** [comment]
well ``discard sdl2_image.quit`` doesn't do what you think what it does. ``sdl2_image.quit`` is just the function symbol of quit, not calling the function or something, and discard says don't do anything with that function symbol. It is basically like ``discard 3``. I fixed this problem from the sdl2 side of things, You have to call this now:

```nim
sdl2_image.quit()
sdl2.quit()
```
