### ISSUE TITLE
Could not specify SDL_WINDOW_FULLSCREEN_DESKTOP on sdl2.setFullscreen

### ISSUE THREAD

**Issue by mizyoukan** [nim-lang/sdl2#50]
I just want to change window's fullscreen state to "fake" fullscreen by the
following code:

```nim
discard window.setFullscreen(SDL_WINDOW_FULLSCREEN_DESKTOP)
```

However `sdl2.setFullscreen`'s flags type is Bool32, so I couldn't specify
`SDL_WINDOW_FULLSCREEN_DESKTOP`.

I think is the better that proc can be specified in Uint32.

**Comment by dom96** [comment]
Thanks for reporting. :)
