### ISSUE TITLE
Unsatisfied dependency: nim (> 0.11.2)

### ISSUE THREAD

**Issue by cnasc** [nim-lang/sdl2#51]
Trying to install through Nimble, I get the following output:

```
Downloading git://github.com/nim-lang/sdl2 into /tmp/nimble_9325/githubcom_nimlangsdl2 using git...
Cloning into '/tmp/nimble_9325/githubcom_nimlangsdl2'...
remote: Counting objects: 23, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 23 (delta 0), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (23/23), 68.79 KiB | 0 bytes/s, done.
Checking connectivity... done.
Unsatisfied dependency: nim (> 0.11.2)
```

And my output for `nim -V` is:

```
Nim Compiler Version 0.11.2 (2015-08-09) [Linux: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

active boot switches: -d:release
```

Obviously my version is not greater than 0.11.2, but as far as I'm aware that's the most recent release.

**Comment by Araq** [comment]
Well I am not sure **why** the dependency is > 0.11.2 but assuming that it is correct, it means you need to use Nim devel aka bootstrapping from github. Can you test if it actually works with 0.11.2? If so, I will gladly update the Nimble requirements.

**Comment by cnasc** [comment]
Hm, I'm having difficulty getting sdl2 to build on my own (or if I'm building it correctly I must not be using it correctly). I think I have some reading up to do.
