### ISSUE TITLE
Has trouble finding sdl_gfx library on debian

### ISSUE THREAD

**Issue by makoConstruct** [nim-lang/sdl2#52]
To reproduce: run examples/sdl_skeleton.nim, fails with `could not load: libSDL2_gfx(|-2.0).so(|.0)`

I'm not sure what this (|-2.0) syntax means or where it's documented (is it a C compiler thing?), it does not seem to allow the nim compiler to find the /usr/lib/libSDL2_gfx.so that I have on my system.

I would appreciate instructions for installing from source so that I can try changing [this line](https://github.com/nim-lang/sdl2/blob/270eb471e5b4c16de8167a7a0cb35ef45c97c4f1/src/sdl2/gfx.nim#L34) to

``` nim
    const LibName = "libSDL2_gfx.so"
```

**Comment by Araq** [comment]
Well the dynlib patterns are documented and should match libSDL2_gfx.so. Not sure what's wrong here.

Installing from source is "git clone" and using ``--noNimblePath --path:path_to_git_repo".

**Comment by makoConstruct** [comment]
Cool. It seems that the problem is sdlgfx installs as libSDL2_gfx-1.0.so.0 (I was misreading before, the other .so was not for SDL2) on my system, not sure where you're getting 2.0 from, source release listed [here](http://cms.ferzkopp.net/index.php/software/13-sdl-gfx) as "Latest" is only version 1.0.1.

**Comment by PeterSR** [comment]
I had the same issue on Arch Linux. Using pacman, I had only installed the `sdl2` package and forgot to install `sdl2_gfx`.

**Comment by krux02** [comment]
I can't reproduce it. You need to have SDL2_gfx installed.
