### ISSUE TITLE
setDrawColor procedure call error

### ISSUE THREAD

**Issue by matkuki** [nim-lang/sdl2#62]
```nim
proc setDrawColor*(renderer: RendererPtr; r, g, b: uint8, a = 255'u8): SDL_Return {.
  importc: "SDL_SetRenderDrawColor", discardable.}

proc setDrawColor*(r: RendererPtr; c: Color) =
  setDrawColor(r, c.r, c.g, c.b, c.a)
```

When calling the first procedure with explicitly named arguments, like for example:
```nim
myRendered.setDrawColor(r=0, g=0, b=0, a=255)
```
it throws an error:
```
Error: cannot bind parameter 'r' twice
```
This didn't happen in a bit older version of the wrapper, as the second **setDrawColor** procedure was not defined yet.
Should this be reported here or in the Nim repository?

Matic

**Comment by fowlmouth** [comment]
This is a Nim bug, but I suspect it could be fixed by changing the second function to
```nim
proc setDrawColor*(renderer: RendererPtr; c: Color) =
  setDrawColor(renderer, c.r, c.g, c.b, c.a)
```
