### ISSUE TITLE
gfx.filledCircleColor color parameter problem?

### ISSUE THREAD

**Issue by matkuki** [nim-lang/sdl2#67]
Hi,
The SDL_gfx documentation says that the 'color' parameter for the gfx.filledCircleColor should be in '0xRRGGBBAA' format:
http://www.ferzkopp.net/Software/SDL_gfx-2.0/Docs/html/_s_d_l__gfx_primitives_8c.html#a39147d1282ec814a1b9e31243aad0359

But when using this in Nim, you have to use '0xAABBGGRR' for it to display the correct color? 
Why is that?

Matic

**Comment by Araq** [comment]
Little endian machine? I don't think it differs from what you need to write in C.

**Comment by matkuki** [comment]
Ok, will look into the SDL_gfx side of it.
Thanks.
