### ISSUE TITLE
Remove the final value in convertSurface proc

### ISSUE THREAD

**Issue by hcorion** [nim-lang/sdl2#68]
Right now the code looks like this:

``` nim
proc convertSurface*(src: SurfacePtr; fmt: ptr PixelFormat;
  flags: cint): SurfacePtr {.importc: "SDL_ConvertSurface".}
```

However, the [docs for SDL_ConvertSurface](https://wiki.libsdl.org/SDL_ConvertSurface) says the following about the flags cint.

> the flags are unused and should be set to 0; this is a leftover from SDL 1.2's API

Therefore, why don't we just remove it to make it easier for the programmer.

**Comment by Araq** [comment]
You cannot remove it because it needs to be binary compatible and on weird archs this then might not be the case. However, the parameter should get a default value of 0.
