### ISSUE TITLE
Creating Renderer Without 'RendererSoftware' Flag Causes Crash

### ISSUE THREAD

**Issue by CaptainKraft** [nim-lang/sdl2#94]
If I use a renderer that is not created with the 'RendererSoftware' flag, I crash when trying to bind a vao with OpenGL immediately after creating a texture using said renderer. I'm not sure why the error happens at the VAO binding call, but adding the flag fixes the problem.

**Comment by Araq** [comment]
This sounds like a common SDL2 gotcha/bug, not a bug in our wrapper.

**Comment by CaptainKraft** [comment]
Oh, sorry about that. Thanks for the heads up
