### ISSUE TITLE
Missing SDL_WINDOW_VULKAN flag.

### ISSUE THREAD

**Issue by Daouki** [nim-lang/sdl2#99]
The library is missing the 'SDL_WINDOW_VULKAN' flag, which I believe was introduced in SDL 2.0.6.
https://github.com/spurious/SDL-mirror/blob/b55bb6ff4889eadd5c2dbd2cceebe4f650b40079/include/SDL_video.h#L122

**Comment by dom96** [comment]
Please make a PR
